version: "3"
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 80:80
    volumes:
      - ./test/docker-stuff/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./test/docker-stuff/web/:/var/www/
      # Enable the following lines when SSL certificates exist:
      # - ./test/docker-stuff/nginx/ssl-site.conf:/etc/nginx/ssl-site.conf
      # - ./tmp/config/pebble":14000/dir/ghost.local/fullchain.pem:/etc/ssl/ghost.local.pem;
      # - ./tmp/config/pebble":14000/dir/ghost.local/privkey.pem:/etc/ssl/ghost.local.key.pem;
  pebble:
    image: "letsencrypt/pebble"
    ports:
      - 14000:14000
      - 15000:15000
    environment:
      PEBBLE_VA_NOSLEEP: 1
    command: pebble -config /test/config/pebble-config.json
    volumes:
      - ./test/docker-stuff/pebble/config.json:/test/config/pebble-config.json
      - ./test/docker-stuff/pebble/pebble.minica.pem:/test/certs/pebble.minica.pem
      - ./test/docker-stuff/pebble/pebble.minica.key.pem:/test/certs/pebble.minica.key.pem
    links:
      - "nginx:ghost.local"
  greenlock:
    image: "node:14-alpine"
    ports:
      - 6660:6660
      - 6661:6661
    working_dir: /home/node/app
    environment:
      NODE_EXTRA_CA_CERTS: '/home/node/pebble.minica.pem'
    command: "yarn start"
    user: "node"
    volumes:
      - ./:/home/node/app
      - ./test/docker-stuff/pebble/pebble.minica.pem:/home/node/pebble.minica.pem
    links:
      - "nginx:ghost.local"
  mysql:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./test/docker-stuff/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: certmanager
